name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            Dependencies :package:
